# Cloud Run service configuration for CKD API
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ckd-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # CPU and Memory limits
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/memory: "2Gi"
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # Timeout for requests (max 3600 seconds for Cloud Run)
        run.googleapis.com/timeout: "300s"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/ckd-api:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              key: gemini-api-key
              name: gemini-secret
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
  traffic:
  - percent: 100
    latestRevision: true